//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WappTestConsumer.ServiceReferenceCheckNumbers {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCheckNumbers.WServiceSoap")]
    public interface WServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckNumber", ReplyAction="*")]
        bool CheckNumber(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckNumberAsync(int number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WServiceSoapChannel : WappTestConsumer.ServiceReferenceCheckNumbers.WServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WServiceSoapClient : System.ServiceModel.ClientBase<WappTestConsumer.ServiceReferenceCheckNumbers.WServiceSoap>, WappTestConsumer.ServiceReferenceCheckNumbers.WServiceSoap {
        
        public WServiceSoapClient() {
        }
        
        public WServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckNumber(int number) {
            return base.Channel.CheckNumber(number);
        }
        
        public System.Threading.Tasks.Task<bool> CheckNumberAsync(int number) {
            return base.Channel.CheckNumberAsync(number);
        }
    }
}
